---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack-crds
  interval: 1h
  path: ./kubernetes/rpi-cluster/apps/monitoring/metrics-server/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: monitoring
  timeout: 5m
  wait: true
