---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-controllers
  interval: 1h0m0s
  path: ./kubernetes/rpi-cluster/apps/monitoring/metrics-server/app/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
