#---
#apiVersion: gateway.networking.k8s.io/v1
#kind: HTTPRoute
#metadata:
#  name: http-link-redirect
#  namespace: home
#spec:
#  parentRefs:
#  - name: private-gateway
#    namespace: common
#    sectionName: http-link
#  hostnames:
#  - "*.k8s-homelab.dev"
#  rules:
#  - filters:
#    - type: RequestRedirect
#      requestRedirect:
#        scheme: https
#        statusCode: 301
#        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  hostnames:
  - "grafana.${INTERNAL_DOMAIN}"
  parentRefs:
  - kind: Gateway
    name: private-gateway
    namespace: network
  rules:
  - backendRefs:
    - kind: Service
      name: kube-prometheus-stack-grafana
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Monitoring system & time series DB"
    gethomepage.dev/group: Monitoring
    gethomepage.dev/icon: prometheus.png
    gethomepage.dev/name: Prometheus
spec:
  hostnames:
  - "prometheus.${INTERNAL_DOMAIN}"
  parentRefs:
  - kind: Gateway
    name: private-gateway
    namespace: network
  rules:
  - backendRefs:
    - kind: Service
      name: kube-prometheus-stack-prometheus
      port: 9090
