---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/rpi-cluster/infrastructure/security/cert-manager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: kube-prometheus-stack-crds
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cert-manager-issuers
#  namespace: flux-system
#spec:
#  interval: 10m
#  path: "./kubernetes/rpi-cluster/infrastructure/security/cert-manager/issuers"
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  wait: true
#  dependsOn:
#    - name: cert-manager
