#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: rook-ceph
#  namespace: flux-system
#spec:
#  interval: 10m
#  path: "./kubernetes/rpi-cluster/infrastructure/storage/rook-ceph/operator"
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  wait: true
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: rook-ceph-cluster
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: rook-ceph
#  interval: 10m
#  path: "./kubernetes/rpi-cluster/infrastructure/storage/rook-ceph/cluster"
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  wait: true
