---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-operator
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/rpi-cluster/infrastructure/storage/rook-ceph/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
