---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stackgres
  namespace: flux-system
spec:
  #decryption:
  #  provider: sops
  #  secretRef:
  #    name: flux-sops
  interval: 1m0s
  path: ./kubernetes/rpi-cluster/apps/datastore/stackgres/operator
  prune: false
  sourceRef:
    kind: GitRepository
    name: stackgres
    namespace: flux-system
  targetNamespace: datastore
