---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stackgres-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: stackgres-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stackgres
        namespace: flux-system
      version: 1.16.x
  interval: 1m0s
