---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-link-redirect
  namespace: common
spec:
  parentRefs:
  - name: example
    namespace: common
    sectionName: http-link
  hostnames:
  - "*.k8s-homelab.dev"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
        port: 443
---
# ArgoCD UI
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: homepage
  namespace: home
spec:
  parentRefs:
  - name: example # gateway name
    namespace: common
    sectionName: https-link
  hostnames:
  - "homepage.k8s-homelab.dev"
  rules:
  - backendRefs:
    - name: homepage
      port: 3000
