---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-repositories
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/rpi-cluster/flux/repositories
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
  #postBuild:
  #  substituteFrom:
  #    - kind: ConfigMap
  #      name: cluster-settings
  #      optional: true
  #    - kind: Secret
  #      name: cluster-secrets
  #      optional: true
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cluster-settings
#  namespace: flux-system
#spec:
#  interval: 30m
#  path: ./kubernetes/rpi-cluster/flux/settings
#  prune: true
#  wait: false
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  decryption:
#    provider: sops
#  postBuild:
#    substituteFrom:
#      - kind: ConfigMap
#        name: cluster-settings
#        optional: true
#      - kind: Secret
#        name: cluster-secrets
#        optional: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/rpi-cluster/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/rpi-cluster/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-repositories
    #- name: cluster-settings
  decryption:
    provider: sops
  #postBuild:
  #  substituteFrom:
  #    - name: cluster-settings
  #      kind: ConfigMap
  #      optional: true
  #    - name: cluster-secrets
  #      kind: Secret
  #      optional: true
