---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkding
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  interval: 1h
  path: ./kubernetes/rpi-cluster/apps/home/linkding/app
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: true
      - kind: Secret
        name: cluster-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: home
  timeout: 5m
  wait: true
