---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chart:
    spec:
      chart: homepage
      interval: 30m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  interval: 30m
  values:
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/kifbv
      services:
        - My First Group:
            - My First Service:
                href: http://localhost/
                description: Homepage is awesome

        - My Second Group:
            - My Second Service:
                href: http://localhost/
                description: Homepage is the best

        - My Third Group:
            - My Third Service:
                href: http://localhost/
                description: Homepage is 😎
      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - search:
            provider: brave
            target: _blank
      kubernetes:
        mode: cluster
      settings:

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true
    
    # This value must be set
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.${INTERNAL_DOMAIN}"

    #ingress:
    #  main:
    #    enabled: true
    #    annotations:
    #      # Example annotations to add Homepage to your Homepage!
    #      gethomepage.dev/enabled: "true"
    #      gethomepage.dev/name: "Homepage"
    #      gethomepage.dev/description: "Dynamically Detected Homepage"
    #      gethomepage.dev/group: "Dynamic"
    #      gethomepage.dev/icon: "homepage.png"
    #    hosts:
    #      - host: homepage.example.com
    #        paths:
    #          - path: /
    #            pathType: Prefix
