---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chart:
    spec:
      chart: homepage
      interval: 30m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  interval: 30m
  values:
    image:
      tag: v1.2
    config:
      bookmarks:
        - Developer:
            - Github:
                - icon: si-github
                  href: https://github.com/kifbv
            - ArchLinux:
                - icon: si-arch-linux
                  href: https://archlinux.org
      services:
        - Home:
            - Linkding:
                icon: linkding.png
                href: https://linkding.${INTERNAL_DOMAIN}
                description: Bookmarks manager

        - Monitoring:
            - Grafana:
                icon: grafana.png
                href: https://grafana.${INTERNAL_DOMAIN}
                description: Observability & data visualisation
            - Prometheus:
                icon: prometheus.png
                href: https://prometheus.${INTERNAL_DOMAIN}
                description: Monitoring system & time series database

      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: false
              cpu: true
              memory: true
              showLabel: true
              label: "rpi-cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - search:
            provider: brave
            target: _blank
      kubernetes:
        mode: cluster
        gateway: true
      settings:

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true
    
    # This value must be set
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.${INTERNAL_DOMAIN}"

    #ingress:
    #  main:
    #    enabled: true
    #    annotations:
    #      # Example annotations to add Homepage to your Homepage!
    #      gethomepage.dev/enabled: "true"
    #      gethomepage.dev/name: "Homepage"
    #      gethomepage.dev/description: "Dynamically Detected Homepage"
    #      gethomepage.dev/group: "Dynamic"
    #      gethomepage.dev/icon: "homepage.png"
    #    hosts:
    #      - host: homepage.example.com
    #        paths:
    #          - path: /
    #            pathType: Prefix
