---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "wildcard-internal"
spec:
  secretName: "wildcard-internal-tls"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.${INTERNAL_DOMAIN}"
