---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: istiod
      version: 1.21.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    pilot:
      env:
        PILOT_ENABLE_AMBIENT: true
        PILOT_ENABLE_HBONE: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    global:
      tls:
        enabled: true
  dependsOn:
    - name: istio-base
  targetNamespace: istio-system