---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      version: 1.17.x
  interval: 30m0s
  values:
    # TODO: enable monitoring (requires prometheus)
    monitoring:
      enabled: false
    # install crds as part of the helm release
    crds:
      enabled: true
    resources:
      requests:
        memory: 128Mi # default value
        cpu: 100m     # half the default value
