---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-repos
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1m0s
  path: ./kubernetes/rpi-cluster/config/repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
