---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: storage
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      version: 1.17.x
  interval: 1h0m0s
  # values for test cluster (1 node only)
  values:
    toolbox:
      enabled: true

    operatorNamespace: storage

    cephClusterSpec:
      skipUpgradeChecks: false
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        allowMultiplePerNode: true
        modules:
          - name: rook
            enabled: true
      dashboard:
        enabled: true
      crashCollector:
        disable: true
      storage:
        useAllNodes: true
        useAllDevices: true

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 1
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true

    monitoring:
      enabled: false

