---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: storage
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      version: 1.17.x
  interval: 1h0m0s
  # values for test cluster (1 node only)
  # TODO: install 2 more nodes :)
  values:
    monitoring:
      enabled: false

    toolbox:
      enabled: true
      
    operatorNamespace: storage # operator installed in storage ns, not default rook-ceph

    cephClusterSpec:
      dataDirHostPath: /var/lib/rook
      skipUpgradeChecks: true
      mon:
        count: 1
        allowMultiplePerNode: true
      mgr:
        count: 1
        allowMultiplePerNode: true
        modules:
          - name: rook
            enabled: true
      dashboard:
        enabled: true
      crashCollector:
        disable: true
      storage:
        useAllNodes: true
        useAllDevices: true
      healthCheck:
        daemonHealth:
          mon:
            interval: 45s

